In [47]:
import numpy as np
from scipy import misc
import matplotlib.pyplot as plt

In [48]:
img_array=misc.face()

In [49]:
img_array

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]

In [50]:
img_array.shape

(768, 1024, 3)

In [60]:
img_array.reshape(768,1024,3,1)

array([[[[121],
         [112],
         [131]],

        [[138],
         [129],
         [148]],

        [[153],
         [144],
         [165]],

        ...,

        [[119],
         [126],
         [ 74]],

        [[131],
         [136],
         [ 82]],

        [[139],
         [144],
         [ 90]]],


       [[[ 89],
         [ 82],
         [100]],

        [[110],
         [103],
         [121]],

        [[130],
         [122],
         [143]],

        ...,

        [[118],
         [125],
         [ 71]],

        [[134],
         [141],
         [ 87]],

        [[146],
         [153],
         [ 99]]],


       [[[ 73],
         [ 66],
         [ 84]],

        [[ 94],
         [ 87],
         [105]],

        [[115],
         [108],
         [126]],

        ...,

        [[117],
         [126],
         [ 71]],

        [[133],
         [142],
         [ 87]],

        [[144],
         [153],
         [ 98]]],


       ...,


       [[[ 87],
         [106],
      

In [61]:
type(img_array)

numpy.ndarray

In [62]:
plt.imshow(img_array)
plt.show()

In [63]:
slice_img=img_array[300:,1000:,:]

In [64]:
plt.imshow(slice_img)
plt.show

<function matplotlib.pyplot.show(*args, **kw)>

In [65]:
x1,x2=np.split(img_array,2)

In [66]:
plt.imshow(x1)
plt.show()

In [67]:
plt.imshow(x2)
plt.show()

In [68]:
import numpy as np
a=np.random.randn(2, 3)

In [69]:
b= np.random.randn(2, 1)
b

array([[0.22294014],
       [1.86034924]])

In [70]:
a+b

array([[-0.00550989,  0.15381102,  0.90882003],
       [ 0.54971438,  0.98344648,  2.32690994]])

In [73]:
a=np.random.randn(12288, 150)
b=np.random.randn(150, 45)
np.dot(a,b).shape

(12288, 45)

In [77]:
a=np.array((3,4))
b=np.array((4,1))

for i in range(3):
  for j in range(4):
    c= a[i][j] + b[j]

IndexError: invalid index to scalar variable.