In [16]:
import numpy as np
import pandas as pd
import math
from numpy.linalg import norm

In [17]:
x=np.arange(1,12288,1)
y=np.tanh(x)
y

array([0.76159416, 0.96402758, 0.99505475, ..., 1.        , 1.        ,
       1.        ])

In [18]:
x=np.random.randn(8).reshape(4,2)
x

array([[-0.69694119,  0.68385479],
       [ 2.61204303,  0.92340632],
       [ 0.56772669,  0.85046087],
       [-0.77011842,  1.93379136]])

In [20]:
norm(x,axis=1,keepdims=True)

array([[0.97641405],
       [2.77045989],
       [1.02254451],
       [2.08149739]])

In [22]:
aaa=np.array([(0,3,4),(2,6,4)])
aaa

array([[0, 3, 4],
       [2, 6, 4]])

In [24]:
norm_aa=norm(aaa,axis=1,keepdims=True)

In [25]:
aaa/norm_aa

array([[0.        , 0.6       , 0.8       ],
       [0.26726124, 0.80178373, 0.53452248]])

In [65]:
import time

x1=np.random.randn(16)
x2=np.random.randn(16)
W=np.random.randn(3,len(x1))
Gdot=np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        Gdot+=W[i,j]*x1[j]

In [66]:
Gdot

array([-6.43750859, -6.43750859, -6.43750859])

In [67]:
np.dot(W,x1)

array([-3.54486939,  1.83288354, -4.72552274])

In [68]:
np.multiply(x1,x2)

array([-0.01788696,  0.40422299,  0.4448078 , -0.45959409,  0.45596082,
        0.21773875,  0.10819205, -0.57979624,  0.08601435,  0.50024936,
        0.12026518, -0.22282897, -0.16469617, -0.65827509,  0.60304837,
       -0.16054937])

In [46]:
x1[j]

0