In [2]:
import numpy as np
#from scipy import ndimage
import sys

In [10]:
for i in range(2 ,14):
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13


In [9]:
np.split(y,(3,6))

[array([0, 1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [17]:
y= np.arange(24).reshape(4,6)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [27]:
x1,x2=np.vsplit(y,2)

print("x1:\n",x1)
print("x2:\n",x2)

x1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
x2:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
