<b>Replace of explicit loops with array expresssions is commonly reffered to as Vectorization</b>

In [94]:
import numpy as np
import random

<b>File Input and Output with Arrays</b>

In [95]:
arr_10=np.random.randn(10)
# saving to disk, file saves with xtension .npy
np.save("mytestarray",arr_10)

In [96]:
np.load("mytestarray.npy")

array([-0.39641792,  0.50568473, -0.39960942,  1.15660606,  1.90050887,
        1.21618915,  0.48724002, -2.29346594,  0.72064356,  1.29457439])

In [97]:
#Saving and Loading big Array
big_array=np.random.randn(200000,50)
np.save("big_arrays",big_array)


In [98]:
#Loading Big data was super fast
np.load("big_arrays.npy")

array([[-0.56873094,  1.06209377, -0.05546778, ...,  0.75892787,
         0.485466  ,  0.1744737 ],
       [ 0.31329445, -1.18449862,  1.09019339, ...,  0.4242234 ,
         1.52799482,  2.03831482],
       [-0.4228519 , -0.5798348 , -0.32855615, ...,  0.66600884,
        -0.00847715,  0.55328375],
       ...,
       [ 1.46313337,  1.07484036,  3.19822479, ...,  1.67483267,
        -0.12637833,  1.03642021],
       [ 0.08751938,  0.48447139, -1.99068407, ..., -1.12783349,
        -0.54159282,  1.31629161],
       [-1.50459118, -0.0896333 , -0.46461056, ..., -0.33646083,
         1.18048831, -3.2650073 ]])

<b> SAVING/ARCHIVING MULTIPLE AND LARGE ARRAYS AND RETRIEVING</b>

In [99]:
big_array1=np.random.randn(200000,50)
big_array2=np.random.randn(200000,50)

<b>Archive Large DataSet and Compressing</b>

In [100]:
np.savez('array_archive.npz',a=big_array1,b=big_array2)  # Data size archive =>160MB

In [101]:
#Saving and Compressing the data for memory efficiency, # Data size archive =>154MB
np.savez_compressed('arrays_compressed.npz', a=big_array1,b=big_array2)

In [102]:
#Loading Data
data_retrieve=np.load('array_archive.npz')

In [103]:
#Access on of the data archived
data_retrieve['a']

array([[ 0.38577554, -2.41825206, -0.14375183, ..., -0.22954232,
        -2.02184934, -1.39329084],
       [ 0.36683976,  0.19105647,  0.82758022, ...,  0.02148178,
        -1.18025757, -0.02382288],
       [-0.07837319,  0.04817798, -0.44488759, ...,  0.45795684,
        -1.66173417,  1.56003616],
       ...,
       [ 1.28130983, -0.39817957,  0.64637852, ...,  0.27306253,
         0.17712939, -1.38747435],
       [-1.154973  ,  0.69192153,  2.31204573, ..., -2.29557196,
        -1.37683887,  0.90508909],
       [-1.44155519,  0.52733571,  1.04232551, ..., -0.20686721,
        -0.78478279, -0.16703634]])

In [104]:
#Access on of the data archived
data_retrieve['b']

array([[ 0.77709719,  0.44290565, -2.27339837, ..., -1.36253283,
        -0.22312597,  0.90670967],
       [ 0.29611549,  0.4413955 , -0.50942514, ...,  1.32589783,
        -1.17973155, -0.74260822],
       [ 0.71658359,  0.0338557 , -0.84507075, ..., -1.13713344,
        -1.3123812 ,  0.78800898],
       ...,
       [ 0.80230377, -1.66059719, -0.41727424, ..., -2.04872667,
        -0.30879314,  0.99793698],
       [-0.5358248 , -0.44923145,  1.06384085, ..., -0.6836259 ,
        -0.61096938,  0.46662921],
       [-0.47264901, -0.82704516, -1.99993845, ..., -1.22750858,
        -1.06331106,  0.45529447]])

In [105]:
x=[y**2 for y in range(5)]
x

[0, 1, 4, 9, 16]

In [106]:
y=[]
for i in range(5):
    i=random.random()
    y.append(i**2)
y

[0.6402826165669414,
 0.29538000840145995,
 0.04911633268126936,
 0.391134248949837,
 0.48605125362349544]

In [107]:
#Vectorized array expressions has replaced the for loop
arr=np.arange(5)
arr1=np.random.randn(5)
np.sqrt(arr**2+arr1**2)

array([0.14191716, 1.64007996, 2.09453129, 3.00618233, 4.02121484])

<b>np.meshgrid function takes two 1D arrays and produces 2D matrices corresponding to all pairs of(x,y) in the two arrays</b>

In [108]:
points=np.arange(-5,5,0.01)

In [109]:
x,y=np.meshgrid(points,points) # 1000 equally spaced points

In [110]:
x

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [111]:
y

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [112]:
y.shape

(1000, 1000)

In [113]:
z=np.sqrt(x**2+y**2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [114]:
import matplotlib.pyplot as plt

In [115]:
plt.imshow(z,cmap=plt.cm.gray);plt.colorbar()

<b>Expression Conditional Logic as Array Operations</b>

<b>The np.where function is a vectorized version of the Ternary expression x if condition else y</b>

In [116]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [117]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [118]:
#Vectorized version of Ternary Operations
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

<b>Apply ternary to a ndarray</b>

In [119]:
arr = np.random.randn(4, 4)
arr

array([[-0.02264456,  0.16360578, -0.25612788, -0.51158734],
       [-1.06677508,  0.2301136 ,  1.5518877 ,  1.05243418],
       [-0.99632444, -1.63109282,  0.37147685,  1.15636901],
       [-0.52565384,  0.98127322,  0.57162012, -0.0773072 ]])

In [120]:
arr>0
arr4=np.where(arr>0,2,2)
arr4

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [121]:
# We returned only the true and the false is the initial value that does not meet the True Value
# This overides the iniotal arr declared above
arr5=np.where(arr>0,2,arr)
arr5

array([[-0.02264456,  2.        , -0.25612788, -0.51158734],
       [-1.06677508,  2.        ,  2.        ,  2.        ],
       [-0.99632444, -1.63109282,  2.        ,  2.        ],
       [-0.52565384,  2.        ,  2.        , -0.0773072 ]])

<b>Mathematical and Statistical Methods</b>

In [122]:
import numpy as np
arr_1=np.random.randn(5,4)
arr_1

array([[-0.58371322, -1.17860026,  0.58726696, -0.38783697],
       [ 0.19671036,  1.18997214, -1.37560449,  1.19580868],
       [-0.46992413,  0.14711982,  0.36708722, -0.38134464],
       [-1.18300691,  0.61697815, -0.71239895,  1.73396233],
       [ 0.47135625, -0.1115329 ,  0.92139651, -1.00113894]])

In [123]:
#Array instance method
arr_1.mean()

0.0021278507110201405

In [124]:
# Mean across the row=> axis=0            
arr_1.mean(axis=0)

array([-0.31371553,  0.13278739, -0.04245055,  0.23189009])

In [125]:
# Mean across the column=> axis=1
arr_1.mean(axis=1)

array([-0.39072087,  0.30172167, -0.08426543,  0.11388365,  0.07002023])

In [126]:
# Numpy function
np.mean(arr_1)

0.0021278507110201405

In [127]:
# Numpy function
# Mean across the row=> axis=0
np.mean(arr_1,axis=0)

array([-0.31371553,  0.13278739, -0.04245055,  0.23189009])

<b>Cumulative calculation</b>

In [128]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [130]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [131]:
arr.cumprod(axis=0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]], dtype=int32)

In [132]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [133]:
# Indices of minimum element
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [134]:
arr_2=np.random.randn(3,2)
arr_2

array([[ 0.23145668, -0.60668064],
       [-0.23227044, -1.00792165],
       [ 0.38552374, -1.12815675]])

In [135]:
arr_2.argmax(axis=0)

array([2, 0], dtype=int64)

## <b>Methods for Boolean Arrays</b>

In [136]:
arr_3 = np.random.randn(50)
arr_3

array([ 1.8284865 ,  0.21986855,  0.1315133 , -0.65526025,  2.17079658,
       -0.08133719, -0.0671152 ,  0.84237127, -1.46203465, -0.80515649,
       -2.14496529, -0.46396257,  0.23237656,  0.95941958,  0.5101985 ,
        0.21107765, -0.63213443, -0.1130959 ,  0.29342638, -1.11886635,
        1.35219169,  0.03639136, -0.47718869,  0.77467775, -0.26287359,
       -0.66874372, -0.80486314, -1.03329989, -0.53174867, -0.78308017,
        0.71024825, -0.38790466,  1.59004375,  0.05170237, -1.04734141,
        0.30603531,  0.91193267, -1.39554521,  0.36955785, -1.22488274,
       -1.51616713,  1.32998931,  0.44472245, -1.07683067,  0.7922384 ,
        1.09339   , -0.09287881,  1.29610548,  0.66429864, -0.89648112])

In [137]:
bool=(arr_3>0).sum()
bool

25

In [138]:
bool_1=arr_3>0

In [139]:
bool_1.any()

True

In [140]:
bool_1.all()

False

In [141]:
arr_3[arr_3>0]

array([1.8284865 , 0.21986855, 0.1315133 , 2.17079658, 0.84237127,
       0.23237656, 0.95941958, 0.5101985 , 0.21107765, 0.29342638,
       1.35219169, 0.03639136, 0.77467775, 0.71024825, 1.59004375,
       0.05170237, 0.30603531, 0.91193267, 0.36955785, 1.32998931,
       0.44472245, 0.7922384 , 1.09339   , 1.29610548, 0.66429864])

## <b>Sorting</b>

In [142]:
arr_6=np.random.randn(7)
arr_6

array([ 0.576552  ,  2.13079424, -0.70636187, -1.43914045,  0.88963644,
       -0.68223151,  0.01363611])

In [143]:
#The sort in place,i.e it will replace the old array
arr_6.sort()
arr_6

array([-1.43914045, -0.70636187, -0.68223151,  0.01363611,  0.576552  ,
        0.88963644,  2.13079424])

In [144]:
arr_7 = np.random.randn(5, 3)
arr_7

array([[ 0.28287977, -0.41149195,  0.36983684],
       [ 0.39201975, -0.46664654, -2.7234423 ],
       [ 0.64204804, -0.0320491 , -0.08579616],
       [-1.19043056, -0.91024221,  0.53751542],
       [ 0.04231757, -1.0467285 ,  0.24158341]])

In [145]:
arr_7.sort(1)
arr_7

array([[-0.41149195,  0.28287977,  0.36983684],
       [-2.7234423 , -0.46664654,  0.39201975],
       [-0.08579616, -0.0320491 ,  0.64204804],
       [-1.19043056, -0.91024221,  0.53751542],
       [-1.0467285 ,  0.04231757,  0.24158341]])

In [146]:
# Getting the 5%or 5th quantile of the datasets
#  quantile is dividing data into parts
large_data=np.random.randn(1000)
large_data[int(0.05*len(arr_7))]

-0.5624702975654462

## <b>Unique and Other Set Logic</b>
Returned sorted unique values

In [147]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [148]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

<b> Constrast to Unique</b>

In [149]:
sorted(set(names))

['Bob', 'Joe', 'Will']

## <b>Linear Algebra</b>

In [150]:
arr_arr=np.random.randn(10).reshape(2,5)
arr_rr=np.random.randn(10).reshape(5,2)

In [151]:
np.dot(arr_arr,arr_rr) # numpy as function

array([[2.48221357, 1.85627094],
       [2.14879903, 0.7163835 ]])

In [152]:
arr_arr.dot(arr_rr)   # array method

array([[2.48221357, 1.85627094],
       [2.14879903, 0.7163835 ]])

In [153]:
np.dot(np.random.randn(6).reshape(2,3),np.ones(3))

array([-1.12628807, -1.58341635])

<b>The @ symbol (as of Python 3.5) also works as an infix operator that performs matrix
multiplication:</b>

In [154]:
arr_arr@arr_rr

array([[2.48221357, 1.85627094],
       [2.14879903, 0.7163835 ]])

In [155]:
from numpy.linalg import inv,qr,det

In [156]:
X = np.random.randn(5, 5)
X

array([[-0.01240077,  0.13169266, -1.00654627, -0.08998375,  0.11276386],
       [ 0.42952062,  0.85562698, -0.43194769, -0.94710062, -0.98612634],
       [-0.40056348,  0.83440757, -0.48355183,  1.10148633, -1.1456735 ],
       [-0.41728255, -0.96827622, -0.67661199,  1.6968202 ,  2.08697152],
       [-1.16996686,  0.95693946,  0.20520191, -0.90595587,  1.33091999]])

In [157]:
mat=X.T.dot(X)


In [158]:
inv(mat)

array([[9.96816823, 8.00532264, 2.85788205, 3.27612434, 4.5544502 ],
       [8.00532264, 7.0119083 , 2.50465594, 2.87977866, 3.78062741],
       [2.85788205, 2.50465594, 1.51682909, 1.18027986, 1.33415898],
       [3.27612434, 2.87977866, 1.18027986, 1.40692153, 1.50113698],
       [4.5544502 , 3.78062741, 1.33415898, 1.50113698, 2.23649909]])

In [159]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -3.55271368e-15, -2.22044605e-15,
        -4.44089210e-16, -3.55271368e-15],
       [ 8.88178420e-15,  1.00000000e+00,  3.99680289e-15,
         2.66453526e-15,  2.66453526e-15],
       [ 0.00000000e+00,  4.44089210e-16,  1.00000000e+00,
         5.55111512e-17,  5.55111512e-16],
       [ 0.00000000e+00, -1.77635684e-15, -8.88178420e-16,
         1.00000000e+00,  1.77635684e-15],
       [ 7.10542736e-15,  0.00000000e+00,  1.77635684e-15,
        -3.55271368e-15,  1.00000000e+00]])

In [160]:
q,r=qr(mat)

In [161]:
#And this returns orthonormal matrix
q

array([[-0.59666869,  0.2933327 ,  0.02193889,  0.29460741,  0.68605216],
       [ 0.21612966, -0.75360167,  0.19436211, -0.15257316,  0.56948863],
       [-0.01987916,  0.01641811, -0.86436626, -0.46023663,  0.20096886],
       [ 0.15643692,  0.47308763,  0.43780553, -0.71338002,  0.22612131],
       [ 0.75657568,  0.34922628, -0.1514574 ,  0.41133818,  0.33689138]])

In [162]:
#This returns an triangular matrix
r

array([[-3.1643022 , -1.17101465, -0.50768305,  2.22233128,  7.57286637],
       [ 0.        , -4.71344425, -0.6508858 ,  5.10093859,  5.08839035],
       [ 0.        ,  0.        , -2.23752625,  2.94645935, -0.71061095],
       [ 0.        ,  0.        ,  0.        , -2.47764412,  1.84691395],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.15063337]])

In [163]:
det(mat)

12.4550240667216

<b>Pseudorandom Number Generation</b>

In [164]:
samples = np.random.normal(size=(4, 4))
samples

array([[-0.59741343, -0.05588555, -1.19728316, -0.61831926],
       [-0.03043667,  1.11377283,  0.20714528,  1.90283736],
       [ 0.37725192,  1.04411717, -2.41515524, -1.28750065],
       [-0.29761555, -0.21210091, -0.55955096, -0.27252092]])

In [165]:
from random import normalvariate
N=1000000
%timeit samples=[normalvariate(0,1) for _ in  range(N)]

1.57 s ± 55.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [166]:
%timeit np.random.normal(size=N)

46.1 ms ± 991 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
#Changing the pseudorandom seed this changes the random generator from standard 0,1 to the seed specified
#np.random.RandomState(1234)

In [179]:
np.random.randn(5)

array([ 0.45677109, -1.2122497 , -0.06534516,  0.79258831, -0.75789643])

In [182]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)

In [183]:
steps = np.where(draws > 0, 1, -1)
steps.cumsum()

array([ -1,  -2,  -3,  -4,  -5,  -4,  -5,  -6,  -7,  -8,  -7,  -6,  -5,
        -4,  -5,  -6,  -5,  -4,  -5,  -4,  -3,  -4,  -5,  -6,  -5,  -6,
        -5,  -6,  -7,  -6,  -7,  -8,  -7,  -6,  -7,  -8,  -9,  -8,  -7,
        -6,  -7,  -6,  -5,  -4,  -5,  -6,  -7,  -8,  -7,  -8,  -7,  -6,
        -5,  -6,  -5,  -6,  -7,  -6,  -5,  -6,  -7,  -8,  -9, -10,  -9,
        -8,  -7,  -6,  -5,  -6,  -5,  -4,  -5,  -6,  -5,  -6,  -7,  -6,
        -5,  -4,  -5,  -4,  -3,  -2,  -1,  -2,  -1,  -2,  -3,  -4,  -5,
        -4,  -3,  -2,  -3,  -2,  -3,  -4,  -3,  -4,  -5,  -6,  -5,  -4,
        -3,  -4,  -5,  -6,  -7,  -6,  -7,  -6,  -7,  -6,  -5,  -6,  -7,
        -6,  -7,  -6,  -5,  -6,  -5,  -6,  -7,  -8,  -9, -10, -11, -10,
        -9,  -8,  -7,  -8,  -9,  -8,  -9,  -8,  -9, -10, -11, -12, -13,
       -14, -15, -16, -17, -16, -17, -16, -15, -14, -15, -16, -15, -14,
       -15, -16, -17, -18, -19, -20, -21, -20, -19, -20, -19, -18, -19,
       -18, -17, -16, -15, -14, -15, -14, -15, -16, -17, -16, -1